### ISSUE TITLE
What do I need to do to make this a proper Java library?

### ISSUE THREAD

**Issue by skyem123** [skyem123/MatcherThing1#8]
- [ ] might want to rename package to `uk.co.skyem.libraries.stringMatcher1`
- [ ] Issue #12 (API Documentation)
- [ ] Issue #10 (CI & Code coverage)
- [x] Issue #7 (If I ever want this in maven central, I only can rely on maven central)
- [ ] Issue #4 would be useful! Slow stuff is not nice to use.
